'use client';

import { TRouteDTO, ROUTES } from '@/lib/settings/routes';

const BREAD_CRUMBS: Record<string, TRouteDTO[]> = {};
BREAD_CRUMBS[ROUTES.HOME.path] = [];
BREAD_CRUMBS[ROUTES.DASHBOARD.path] = [ROUTES.DASHBOARD];
BREAD_CRUMBS[ROUTES.PROFILE.path] = [ROUTES.PROFILE];
BREAD_CRUMBS[ROUTES.DEBUG.path] = [ROUTES.DEBUG];
BREAD_CRUMBS[ROUTES.SAMPLE_CLIENT.path] = [ROUTES.DEBUG, ROUTES.SAMPLE_CLIENT];
BREAD_CRUMBS[ROUTES.SAMPLE_SERVER.path] = [ROUTES.DEBUG, ROUTES.SAMPLE_SERVER];

export { BREAD_CRUMBS };
